"""Add gamification stats to user

Revision ID: 7dc0795244d4
Revises: 4dc83fed194b
Create Date: 2026-01-10 18:37:41.155153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc0795244d4'
down_revision: Union[str, None] = '4dc83fed194b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_xp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'level')
    op.drop_column('users', 'total_xp')
    # ### end Alembic commands ###
