"""Add xp_breakdown to user

Revision ID: 8bfb959fc625
Revises: 7dc0795244d4
Create Date: 2026-01-10 22:57:22.912066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bfb959fc625'
down_revision: Union[str, None] = '7dc0795244d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xp_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp_breakdown')
    # ### end Alembic commands ###
