"""Add Source B

Revision ID: 9b4e3de00a0e
Revises: faa0e90ae89e
Create Date: 2026-01-09 16:38:22.100465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4e3de00a0e'
down_revision: Union[str, None] = 'faa0e90ae89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drops', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('drops', sa.Column('source_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drops', 'source_type')
    op.drop_column('drops', 'source_url')
    # ### end Alembic commands ###
