"""Add submission_type to drops

Revision ID: cc416f04b92a
Revises: dfae36fd4e9a
Create Date: 2026-01-09 20:00:29.634919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc416f04b92a'
down_revision: Union[str, None] = 'dfae36fd4e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
