"""Add submission_type to drops

Revision ID: dfae36fd4e9a
Revises: 9b4e3de00a0e
Create Date: 2026-01-09 18:41:50.637250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfae36fd4e9a'
down_revision: Union[str, None] = '9b4e3de00a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drops', sa.Column('submission_type', sa.Enum('CODE', 'LINK', 'IMAGE', 'FILE', name='submission_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drops', 'submission_type')
    # ### end Alembic commands ###
