"""Add soft deletes and split profiles

Revision ID: fd767298ad41
Revises: 53a04b630b38
Create Date: 2026-02-25 00:31:18.356753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd767298ad41'
down_revision: Union[str, None] = '53a04b630b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startup_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('talent_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('xp_score', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # op.add_column('messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # op.add_column('profiles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    pass
    # op.add_column('submissions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('submissions', 'deleted_at')
    pass
    op.drop_column('profiles', 'deleted_at')
    op.drop_column('messages', 'deleted_at')
    op.drop_table('talent_profiles')
    op.drop_table('startup_profiles')
    # ### end Alembic commands ###
